### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by Lalman888** [intelowlproject/intelowlproject.github.io#1]
Can I do contributions in this project ?

**Comment by abheektripathy** [comment]
hey, @Lalman888 im working on this as part of my gsoc proposal, you won't be able to contribute here till the first release.
till then you might wanna pick up some other frontend issues at the [intelowl repository](https://github.com/intelowlproject/IntelOwl), you'll get familiar with the codebase and style there.
Make sure to read the [contribute docs](https://intelowl.readthedocs.io/en/latest/Contribute.html) as well!
