### ISSUE TITLE
feature: add markdown plugins to blogs for better customisability.

### ISSUE THREAD

**Issue by abheektripathy** [intelowlproject/intelowlproject.github.io#11]
We could setup some mdx plugins with contentlayer for better blog customisability.

these would be a good place to start.
1. [remark-gfm](https://github.com/remarkjs/remark-gfm) to support [GitHub Flavored Markdown](https://github.github.com/gfm/).
2. [rehype-prism-plus](https://github.com/timlrx/rehype-prism-plus) to render syntax highlighting in code blocks.
3. [rehype-code-titles](https://github.com/rockchalkwushock/rehype-code-titles) to render code block titles.
4. [rehype-accessible-emojis](https://www.npmjs.com/package/rehype-accessible-emojis) to provide accessibility to emojis.

Reference [Doc.](https://contentlayer.dev/docs/sources/files/mdx-d747e46d#mdx-plugins-remarkrehype:~:text=MDX%20Plugins%20(remark/rehype))

**Comment by sedbytes** [comment]
I'd be happy to give this a shot. May I work on this?

**Comment by rabbabansh** [comment]
I tried to implement this, but I think is bugged with the support for gfm right now.

https://github.com/shadcn/next-contentlayer/issues/20
https://github.com/shadcn/next-contentlayer/issues/6
https://github.com/shadcn/next-contentlayer/pull/17

:(

**Comment by g4ze** [comment]
i think this issue is closed under #33
