### ISSUE TITLE
Blog Posts: max-width

### ISSUE THREAD

**Issue by mhils** [intelowlproject/intelowlproject.github.io#14]
First off, the new IntelOwl website looks great!

One suggestion for improvement: limit the line length / blog post width. It's hard to read on large monitors:

<img width="1902" alt="Screenshot 2023-09-15 at 11 29 45" src="https://github.com/intelowlproject/intelowlproject.github.io/assets/1019198/218937f1-1d9e-4cb6-beef-d05e16aa0909">

See https://baymard.com/blog/line-length-readability for some research on that. :)

**Comment by mlodic** [comment]
thank you for the suggestion, we'll check it :)

**Comment by keshav861** [comment]
can i contribute in it?

**Comment by keshav861** [comment]
i have send PR you can see it

**Comment by mlodic** [comment]
merged, thank you!
