### ISSUE TITLE
Change the Header positioning.

### ISSUE THREAD

**Issue by PrgrmrHarshShukla** [intelowlproject/intelowlproject.github.io#17]
Currently the Header is **fixed** on the screen.
It keeps a part of the screen for itself.

https://github.com/intelowlproject/intelowlproject.github.io/assets/125105825/e4f85a5a-dea6-43e7-9a74-af681d45cf15

If we could change the positioning of the Header, it would free up some space for a better view of the UI as the user scrolls.

**Comment by PrgrmrHarshShukla** [comment]
Hello @mlodic Sir,
I have raised the issue as discussed on Slack.
Please assign this to me so I can put forward the possible solutions.

Regards,
Harsh

**Comment by mlodic** [comment]
I thought that it was a matter of the real IntelOwl application, not of this site.

In this case this behavior is intended and won't be changed.

Thank you anyway for raising the issue

**Comment by PrgrmrHarshShukla** [comment]
Oh, 
I am so sorry for the misunderstanding Sir.
Will take care afterwards.
