### ISSUE TITLE
Scroll Bar Appearance

### ISSUE THREAD

**Issue by g4ze** [intelowlproject/intelowlproject.github.io#18]
Hey there! The website looks great but the grey scroll bars do not exactly seem to align with the designs of the website. It's not a major functionality problem but I think they can be styled better.
[sreenrec](https://github.com/intelowlproject/intelowlproject.github.io/assets/102874321/42b5c6d9-7985-44b9-b866-0d76efa11d2f)

**Comment by mlodic** [comment]
hey do you have any suggestion about how changing this?

**Comment by g4ze** [comment]
I did some prying into the code base. It seems to be bug arriving from the tailwind framework opted during the dev stages. As per my observations, the scroll bar looks fine whenever we are NOT in desktop view. Another small bug here seems that the website overflows a bit making the browser render another bottom slider. This as well seems to be a bug from the tailwind library itself. I tried tuning the global.css a bit and have implemented some scrollbar styling. I've also made sure that the bottom slider is not visible and x-axis overflow is hidden.
aded:
`
body::-webkit-scrollbar {
  width: 8px;
}
body::-webkit-scrollbar-track {
  background-color: #0E1016;
  
}

body::-webkit-scrollbar-thumb {
  background-color: #2c2c2c;
  
}

body::-webkit-scrollbar-thumb:hover {
  background-color: #555;
}`

This solves all the small bugs involved.

**Comment by g4ze** [comment]
I did some prying into the code base. It seems to be bug arriving from the tailwind framework opted during the dev stages. As per my observations, the scroll bar looks fine whenever we are NOT in desktop view. Another small bug here seems that the website overflows a bit making the browser render another bottom slider. This as well seems to be a bug from the tailwind library itself. I tried tuning the global.css a bit and have implemented some scrollbar styling. I've also made sure that the bottom slider is not visible and x-axis overflow is hidden.
aded:
```

body::-webkit-scrollbar {
width: 8px;
}
body::-webkit-scrollbar-track {
background-color: #0E1016;

}

body::-webkit-scrollbar-thumb {
background-color: #2c2c2c;

}

body::-webkit-scrollbar-thumb:hover {
background-color: #555;
}
```

This solves all the small bugs involved for the desktop web view and at the same time maintains the styling for mobile/other web views.

**Comment by mlodic** [comment]
ok can you plz open a PR? ty :)

**Comment by g4ze** [comment]
sure!

**Comment by g4ze** [comment]
I can't seem to find Pr format for this particular repo; adding a pr :3
